### ISSUE TITLE
重构

### ISSUE THREAD

**Issue by versun** [versun/RSS-Translator#95]
记录重构进度，不定时更新
开发日记：https://github.com/rss-translator/RSS-Translator/blob/v2/dev-diaries/versun-dev-diary.md
相关链接：
https://github.com/PyHAT-stack/awesome-python-htmx
https://pocketbase.io/demo/
https://github.com/troxler/awesome-css-frameworks?tab=readme-ov-file
https://reflex.dev/
https://github.com/adamghill/django-unicorn
https://reactpy.dev/docs/index.html
https://streamlit.io/
https://htmx.org/
https://github.com/togethercomputer/helm/blob/69af78fc312230ea109bad666b3fd89e903147e1/src/helm/proxy/models.py#L71
https://github.com/togethercomputer/helm/blob/69af78fc312230ea109bad666b3fd89e903147e1/src/helm/proxy/clients/openai_client.py#L39
https://github.com/BerriAI/litellm

[newsletter_summarize](https://github.com/ComposioHQ/composio/tree/master/python/examples/newsletter_summarizer)

### Todo
- [ ] 后端API
  - [ ] 数据库模型
  - [ ] 基础框架
  - [ ] 核心逻辑
  - [ ] 任务管理
  - [ ] 单独管理feed post
      - [ ] 使用reader包
  - [ ] 支持google reader api
  - [ ] 添加passwall功能
  - [ ] 优化原文获取
      - [ ] 选择使用jina.ai的reader api: https://[r.jina.ai/rsstranslator.com](https://r.jina.ai/rsstranslator.com)
  - [ ] 支持阅读状态同步
  - [ ] 翻译引擎优化
      - [ ] 直接使用litellm包
      - [ ] 每个翻译服务做为一个单独实例，而不是每个任务新建一个实例
      - [ ] 翻译引擎添加tpm和rpm
      - [ ] 添加翻译引擎pool功能（可做为可选插件，使用litellm server）
  - [ ] 插件功能 
- [ ] 前端
   - buttondown的dashboard挺不错的，可以参考
- [ ] 新旧版本数据导入导出

其他正在考虑的功能
- [ ] 类buzzing的前端页面
- [ ] archive功能
